modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/srcres258/CreativeTabSearch/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/srcres258/CreativeTabSearch"
authors="${mod_authors}"
displayTest="IGNORE_ALL_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="mixins.creativetabsearch.json"
